name: Deploy

on:
  push:

env:
  STUB_DIR: ./deploy/examples/default/stubs/argo-gitops-repo
  MANIFEST_DIR: manifests/my-platform/overlays/dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SetUp
        run: |
          cd "${STUB_DIR}"

          git config --global user.email 'stub@user.me'
          git config --global user.name 'stub user'

          git init -b main
          git remote add origin .

          git add .
          git commit -m 'Bootstrap stub repo'
          git push -u origin main

      - uses: ./deploy
        with:
          environment: dev
          platform: my-platform
          deploy_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          gitlab_known_hosts: ${{ vars.GITLAB_KNOWN_HOSTS }}
          argo_folder: ${{ env.STUB_DIR }}
          changes: |
            my-service,true,${{ github.sha }}

            my-other-service,       true, ${{ github.sha }}, v1.0.0
            my-yet-another-service, true, ${{ github.sha }}, my-yet-another=v2.0.0

      - name: Resulting kustomization.yaml
        run: cat "${STUB_DIR}/${MANIFEST_DIR}/kustomization.yaml"

      - run: pip install pyyaml

      - working-directory: "${{ env.STUB_DIR }}/${{ env.MANIFEST_DIR }}"
        shell: python {0}
        run: |
          import os
          import yaml

          with open('kustomization.yaml') as f:
            kustomization = yaml.safe_load(f)

            for img in kustomization['images']:
              print(f"{img['name']=}, {img['newTag']=}, {os.environ['GITHUB_SHA']=}")
              assert img['newTag'] == os.environ['GITHUB_SHA']

            assert kustomization['configMapGenerator'][0]['literals'][1] == f"APP_RELEASE=v1.0.0"
            assert kustomization['configMapGenerator'][1]['literals'][0] == f"APP_RELEASE=v2.0.0"
    
