name: Production

on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md
      - version.txt
      - .release-please-manifest.json

env:
  environment: prd
  platform: devops-stub-svc

jobs:
  src-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      number: ${{ steps.get_issue_number.outputs.result }}
    steps:
      - id: get_issue_number
        uses: actions/github-script@v6
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          result-encoding: string

  build-release-list:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    needs:
      - src-pr
    outputs:
      services: ${{ steps.build-release-list.outputs.services }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./build-release-list
        id: build-release-list
        with:
          release-candidate-tag: release-pr-${{ needs.src-pr.outputs.number }}
          platform: actions
          services: |
            [
              "devops-stub-svc"
            ]


  release-please:
    runs-on: ubuntu-latest
    needs:
      - src-pr
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: ./release-to-prd-please
        id: release
        with:
          release-token: ${{ secrets.RA_GH_RELEASE_TOKEN }}

      - name: tag major and minor versions
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/googleapis/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}


