name: Staging

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - version.txt
      - .release-please-manifest.json

env:
  environment: stg
  platform: devops-stub-svc

jobs:
  test-sh:
    uses: ./.github/workflows/test-sh.yaml
    secrets: inherit

  test-python:
    uses: ./.github/workflows/test-python.yaml
    secrets: inherit

  test-e2e:
    uses: ./.github/workflows/test-e2e.yaml
    secrets: inherit

  devops-stub-svc:
    uses: ./.github/workflows/devops-stub-svc.yaml
    secrets: inherit
    needs:
      - test-sh
      - test-python
      - test-e2e

  release-please:
    runs-on: ubuntu-latest
    needs:
      - devops-stub-svc
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      pre_release_tag: ${{ steps.release.outputs.pre_release_tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./release-to-stg-please
        id: release
        with:
          release-token: ${{ secrets.RA_GH_RELEASE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
